### ISSUE TITLE
add the Hacktoberfest tag

### ISSUE THREAD

**Issue by arbazdiwan** [codeitbijay/Hacktoberfest2k20#26]
Please add the **hacktoberfest** tag in the repository. 
Otherwise, the pull requests made in this repository will not be counted towards the Hacktoberfest-2020.

following is the status of my pull request on this repository 

Hacktoberfest page says : 

<quote>

_**Ineligible Repository**
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate._

</quote>

**Comment by saippuakauppias** [comment]
+1

**Comment by codeitbijay** [comment]
Kindly @arbazdiwan @saippuakauppias tell me how to add that hacktober feast tag , i will do it asap , 
Thanks to both of you notifying me ,
Regrads

**Comment by codeitbijay** [comment]
Hacktober feast tag had been added to every Pr @saippuakauppias @arbazdiwan 
Thankyou for your interest

**Comment by codeitbijay** [comment]
Hey can you please close the issue !! 
Regrads 
Bijay

**Comment by Scientist69** [comment]
how can we add hacktober tag and also are we allowed to write any code of our choice?

**Comment by arbazdiwan** [comment]
it is **Hacktoberfest** not **Hacktoberfeast**.

see this...
https://github.com/codeitbijay/Hacktoberfest2k20/labels

**Comment by codeitbijay** [comment]
Okay fine ; i will make the changes soon

**Comment by Scientist69** [comment]
we can solve issues of this repo for hacktoberfest right??

**Comment by codeitbijay** [comment]
Yaa ok fine, I will do it asap

**Comment by codeitbijay** [comment]
@arbazdiwan **I have made the following changes as you told , if any problem persists comment out here I will fix it soon , sorry for the inconveniences.  And if anyone have not got the label or missed out plz comment out here i will fix it out asap .**

**Comment by Scientist69** [comment]
can we write any code of our choice?

**Comment by codeitbijay** [comment]
Ya, brother you can !

**Comment by syeedameen** [comment]
@codeitbijay  Greetings of the day Sir , I am a beginner in open source .
I would like to work on this.
And I am also taking part in Hacktoberfest , So can I contribute to it in October.

**Comment by arbazdiwan** [comment]
after solving a lot of build issues, I am able to successfully run the App (I think there should me steps written in readme.md file to configure the project).

I've received the OTP, it is asking me for roll number. Not accepting any random roll number.

What to do now? 
where to find and store this data?
